name: spy_on_your_work
description: "A new Flutter project."
publish_to: "none"

version: 2.0.0

environment:
  sdk: ^3.9.0

dependencies:
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_rust_bridge: 2.11.1
  isar_community: ^3.2.0-dev.2
  isar_community_flutter_libs: ^3.2.0-dev.2
  logging: ^1.3.0
  path_provider: ^2.1.5
  riverpod: ^2.6.1
  rust_lib_spy_on_your_work:
    path: rust_builder
  toastification: ^3.0.3
  window_manager: ^0.5.1
  go_router: ^16.2.0
  flutter_layout_grid: ^2.0.8
  calendar_view: ^1.4.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.2
  integration_test:
    sdk: flutter
  isar_community_generator:
    git:
      url: https://github.com/callumw-k/isar-community
      ref: migrating-to-source_gen-3
      path: packages/isar_community_generator/

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

icons_launcher:
  image_path: "assets/icon.png"
  platforms:
    windows:
      enable: true
    linux:
      enable: true
    macos:
      enable: true
