// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../spy/model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<Application> applicationInfoStream() =>
    RustLib.instance.api.crateApiSpyApiApplicationInfoStream();

void startSpy() => RustLib.instance.api.crateApiSpyApiStartSpy();

bool getSpyStatus() => RustLib.instance.api.crateApiSpyApiGetSpyStatus();

void initSavePath({required String path}) =>
    RustLib.instance.api.crateApiSpyApiInitSavePath(path: path);

void initScreenshotApps({required List<String> v}) =>
    RustLib.instance.api.crateApiSpyApiInitScreenshotApps(v: v);

void insertScreenshotApps({required String v}) =>
    RustLib.instance.api.crateApiSpyApiInsertScreenshotApps(v: v);

void removeScreenshotApps({required String v}) =>
    RustLib.instance.api.crateApiSpyApiRemoveScreenshotApps(v: v);
